# Generated by Django 4.2.12 on 2024-05-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedPDF',
        ),
    ]
